### PR TITLE
init -- generates config template

### PR DESCRIPTION
**Pull request by kitty-gitbabel**
## Tickets

* 🔐[Clubhouse Story CH956](https://app.clubhouse.io/gitbabel/story/956/initial-cli-tooling-to-generate-gitbabelconfig)

## Overview

First attempt at gitBabel CLI.  Creates gitBabel Config template.

## Verification Steps

* `npm test`
image

* `gitbabel init`
  * scenario 1: `.gitbabel/config.json does not exists`
    * user notified file has been saved to `.gitbabel/config.json`
  * scenario 2: `.gitbabel/config.json exists`
    * user is prompted whether to overwrite existing file
      * yes: user notified file has been saved
      * no: user notified file has not been overwritten

## Code Review Checklist

- [ ] Checklist N/A for this PR  (for those 1 lines)

#### Risk
- [ ] Were there new patterns created for the implementation?

### Tests Pass
- [x] Were there tests written?
- [x] Did you run any manual tests?

### Docs
- [ ] Are changes required for docs?
    - [ ] `readme.md` was updated?
    - [ ] Additional documentation required for `docs/`?
- [x] No Doc Changes.

### CODE REVIEW

**Comment by kitty-gitbabel** [comment]
Thoughts on:
*  whether additional documentation is necessary outside of README
*  does it make sense to include clubhouse ticket, since that's not accessible to the public?  should we start leveraging github issues for this project?

**Review by mgan59 — APPROVED** [review]
Pulled and tested, looks great 💯

**Comment by mgan59** [comment]
> whether additional documentation is necessary outside of README

Think the Readme is fine, when we add additional functionality we can expand docs.  

> Does it make sense to include clubhouse ticket, since that's not accessible to the public? should we start leveraging github issues for this project?

That is an interesting question, and first thing I asked myself when I saw you had dropped the link in for clubhouse.  Fine with leaving clubhouse for now, I put a lock icon on it was a caution for anyone landing in here.  And think adopting github issues for the project would be sensible.


> Including comments in template will cause error during processing, we need a separate doc to explain how template works....but where should the doc live? We can definitely add something brief in the README but let me know if you think we need to have a dedicated doc.

Thats a bummer.  Think we can defer on putting into the README.  Definitely want standalone docs -- was thinking we would create the `academy` repo inside of this org now.  And we could start to assembly a standalone Knowledge base there, and we put together the config instructions there?

**Comment by kitty-gitbabel** [comment]
> Think the Readme is currently 👍 -- when we add additional functionality we can expand docs.

👍 

> That is an interesting question, and first thing I asked myself when I saw you had dropped the link in for clubhouse. Fine with leaving clubhouse for now (for us), I put a lock icon on it was a caution for anyone landing in here. And think adopting github issues for the project would be sensible so that we can give some transparency to the broader community what we are doing?

Agree.  We just have to figure out how we want to have it work with our internal process.  Maybe have a clubhouse ticket for internal AND a github issue for external transparency.

> Thats a bummer. Think we can defer on putting into the README. Definitely want standalone docs -- was thinking we would create the `academy` repo inside of this org now. And we could start to assembly a standalone Knowledge base there, and we put together the config instructions there?

I cleared out the template a bit more to avoid confusion when looking at the template.  Think this is definitely a good time to start standalone docs.

**Comment by mgan59** [comment]
Looks Perfect 💯 -- g2m 👍

**Pull request merged**
